#!/bin/sh

source ../.common

#export CONFIG_VSFTPD_VERSION=3.0.5
#export VSFTPD_OUTPUT_PATH=${OUTPUT_PATH}/${VSFTPD}

export CONFIG_OPENSSL=1.1.1k
export OPENSSL_OUTPUT_PATH=${VSFTPD_OUTPUT_PATH}
export LIBCAP_OUTPUT_PATH=${VSFTPD_OUTPUT_PATH}

export OPENSSL_OUTPUT_PATH_HOST=${VSFTPD_OUTPUT_PATH_HOST}
export LIBCAP_OUTPUT_PATH_HOST=${VSFTPD_OUTPUT_PATH_HOST}

make_vsftpd
#make_vsftpd_host
