#!/bin/sh
source ../.common

export CONFIG_MTD_UTILS_VERSION_2X=2.1.2
#export CONFIG_LZO_VERSION=2.08
#export CONFIG_ZLIB_VERSION=1.2.11
#export CONFIG_E2FSPROGS_VERSION=1.47.3

export MTD_UTILS_OUTPUT_PATH_2X=${OUTPUT_PATH}/${MTD_UTILS}
#export E2FSPROGS_OUTPUT_PATH=${OUTPUT_PATH}/${E2FSPROGS}
#export ZLIB_OUTPUT_PATH=${OUTPUT_PATH}/${ZLIB}
#export LZO_OUTPUT_PATH=${OUTPUT_PATH}/${LZO}

make_mtd_utils_2x
