#!/bin/sh

source ../.common

#export CONFIG_LIBSRTP_VERSION=2.5.0
#export LIBSRTP_OUTPUT_PATH=${OUTPUT_PATH}/${LIBSRTP}
#export LIBSRTP_OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}/${LIBSRTP}

export CONFIG_OPENSSL=1.1.1k
export OPENSSL_OUTPUT_PATH=${LIBSRTP_OUTPUT_PATH}
export OPENSSL_OUTPUT_PATH_HOST=${LIBSRTP_OUTPUT_PATH_HOST}

make_libsrtp
#make_libsrtp_host
