#!/bin/bash

source ../.common

#export CONFIG_V4L2RTSPSERVER_VERSION=master
export CONFIG_LIVE555_VERSION=latest

#export V4L2RTSPSERVER_OUTPUT_PATH=${OUTPUT_PATH}/${V4L2RTSPSERVER}
#export V4L2RTSPSERVER_OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}/${V4L2RTSPSERVER}


export OPENSSL_OUTPUT_PATH=${OUTPUT_PATH}/${V4L2RTSPSERVER}
export LIVE555_OUTPUT_PATH=${OUTPUT_PATH}/${V4L2RTSPSERVER}

export OPENSSL_OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}/${V4L2RTSPSERVER}
export LIVE555_OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}/${V4L2RTSPSERVER}

make_v4l2rtspserver
#make_v4l2rtspserver_host
