#!/bin/sh

source ../.common

#export CONFIG_LIBSDL_TTF_VERSION=2.0.15
#export CONFIG_LIBSDL_V2_VERSION=2.0.12
#export CONFIG_FREETYPE_VERSION=2.10.4

#export LIBSDL_TTF_OUTPUT_PATH=${OUTPUT_PATH}/${LIBSDL_TTF}
export LIBSDL_V2_OUTPUT_PATH=${LIBSDL_TTF_OUTPUT_PATH}
export FREETYPE_OUTPUT_PATH=${LIBSDL_TTF_OUTPUT_PATH}


make_libsdl_ttf


#export LIBSDL_TTF_OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}/${LIBSDL_TTF}
export LIBSDL_V2_OUTPUT_PATH_HOST=${LIBSDL_TTF_OUTPUT_PATH_HOST}
export FREETYPE_OUTPUT_PATH_HOST=${LIBSDL_TTF_OUTPUT_PATH_HOST}

#make_libsdl_ttf_host
